# Start with the official Nginx image
FROM nginx:latest

# Remove the default Nginx config
RUN rm /etc/nginx/conf.d/default.conf

# Copy our custom config file into the image
COPY nginx.conf /etc/nginx/conf.d/
